add tests in CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,14 +3,59 @@ name: CI Docker and Helm
 on:
   push:
     branches:
-      - workflow/api-improve
+      - workflow/add-test
 
 env:
   IMAGE_NAME: bouyguestelecom/tada
   CHART_PATH: ./opensource
 
 jobs:
+  tests:
+    runs-on: ubuntu-latest
+    steps:
+      -   name: Checkout repository
+          uses: actions/checkout@v2
 
+      -   name: Set up Docker Buildx
+          uses: docker/setup-buildx-action@v1
+
+      -   name: Log in to Docker Hub
+          uses: docker/login-action@v2
+          with:
+            username: ${{ secrets.DOCKER_USERNAME }}
+            password: ${{ secrets.DOCKER_PASSWORD }}
+
+      -   name: Set up Docker Compose
+          run: |
+            cd ${{ github.workspace }}
+            docker-compose up -d
+
+      -   name: Wait for services to be healthy
+          run: |
+            timeout=30
+            echo "Waiting for Docker services to be healthy..."
+            while ! ( docker-compose ps | grep -q "healthy" ) && [ $timeout -gt 0 ]; do
+              sleep 1
+              timeout=$((timeout-1))
+            done
+            if [ $timeout -eq 0 ]; then
+              echo "Services did not become healthy in time. Aborting."
+              docker-compose down
+              exit 1
+            fi
+
+      -   name: Run Tests
+          run: |
+            cd ${{ github.workspace }}/TESTS
+            bru run flows/ --env Local -r --bail
+          continue-on-error: false
+
+      -   name: Clean up Docker Compose
+          run: docker-compose down
+
+      -   name: Report test results
+          if: failure()
+          run: echo "Tests failed."
   determine-version:
     runs-on: ubuntu-latest
     outputs:
@@ -159,9 +204,9 @@ jobs:
         with:
           version: v3.11.1
 
-      - name: Package Helm char
+      - name: Package Helm chart
         run: |
           helm package opensource --version "${{ needs.determine-version.outputs.new_version }}"
       - name: Push Helm chart to Docker Hub
         run: |
-          helm push $(ls *.tgz) oci://registry-1.docker.io/bouyguestelecom
+          helm push $(ls *.tgz) oci://registry-1.docker.io/bouyguestelecomcharts
